export const types = {
    SET_STARSHIPS: 'SET_STARSHIPS',
    SET_STARSHIP_INFO: 'SET_STARSHIP_INFO',
    SET_STARSHIP_FILMS_SAGA: 'SET_STARSHIP_FILMS_SAGA',
    SET_STARSHIP_PILOTS_SAGA: 'SET_STARSHIP_PILOTS_SAGA',
};