export const types = {
    SET_SPECIES: 'SET_SPECIES',
    SET_SPECIE_INFO: 'SET_SPECIE_INFO',
    SET_SPECIE_FILMS_SAGA: 'SET_SPECIE_FILMS_SAGA',
    SET_SPECIE_PEOPLE_SAGA: 'SET_SPECIE_PEOPLE_SAGA',
    SET_SPECIE_HOMEWORLD_SAGA: 'SET_SPECIE_HOMEWORLD_SAGA',
};