export const types = {
    SET_CHARACTERS: 'SET_CHARACTERS',
    SET_CHARACTER_INFO: 'SET_CHARACTER_INFO',
    SET_CHARACTER_FILMS_SAGA: 'SET_CHARACTER_FILMS_SAGA',
    SET_CHARACTER_SPECIES_SAGA: 'SET_CHARACTER_SPECIES_SAGA',
    SET_CHARACTER_VEHICLES_SAGA: 'SET_CHARACTER_VEHICLES_SAGA',
    SET_CHARACTER_STARSHIPS_SAGA: 'SET_CHARACTER_STARSHIPS_SAGA',
    SET_CHARACTER_HOMEWORLD_SAGA: 'SET_CHARACTER_HOMEWORLD_SAGA',
};