export const types = {
    SET_PLANETS: 'SET_PLANETS',
    SET_PLANET_INFO: 'SET_PLANET_INFO',
    SET_PLANET_FILMS_SAGA: 'SET_PLANET_FILMS_SAGA',
    SET_PLANET_RESIDENTS_SAGA: 'SET_PLANET_RESIDENTS_SAGA',
};