export const types = {
    SET_VEHICLES: 'SET_VEHICLES',
    SET_VEHICLE_INFO: 'SET_STARSHIP_INFO',
    SET_VEHICLE_FILMS_SAGA: 'SET_VEHICLE_FILMS_SAGA',
    SET_VEHICLE_PILOTS_SAGA: 'SET_VEHICLE_PILOTS_SAGA',
};