export const types = {
    SET_LIST: 'SET_LIST',
    SET_INFO_DATA: 'SET_INFO_DATA',
    SET_LINKS_FILMS: 'SET_LINKS_FILMS',
    SET_LINKS_SPECIES: 'SET_LINKS_SPECIES',
    SET_LINKS_VEHICLES: 'SET_LINKS_VEHICLES',
    SET_LINKS_RESIDENTS: 'SET_LNKS_RESIDENTS',
    SET_LINKS_CHARACTERS: 'SET_LINKS_CHARACTERS',
    SET_LINKS_PLANETS: 'SET_LINKS_PLANETS',
    SET_LINKS_STARSHIPS: 'SET_LINKS_STARSHIPS',
};