export const types = {
    // SET_CHARACTERS_DATA: "SET_CHARACTERS_DATA",
    // SET_CHARACTER_INFO_DATA: "SET_CHARACTER_INFO_DATA",
    // SET_CHARACTER_FILMS: "SET_CHARACTER_FILMS",
    // SET_CHARACTER_SPECIES: 'SET_CHARACTER_SPECIES',
    // SET_CHARACTER_VEHICLES: 'SET_CHARACTER_VEHICLES'
};