export const types = {
    SET_FILMS: 'SET_FILMS',
    SET_FILM_INFO: 'SET_FILM_INFO',
    SET_FILM_CHARACTERS_SAGA: 'SET_FILM_CHARACTERS_SAGA',
    SET_FILM_PLANETS_SAGA: 'SET_FILM_PLANETS_SAGA',
    SET_FILM_STARSHIPS_SAGA: 'SET_FILM_STARSHIPS_SAGA',
    SET_FILM_VEHICLES_SAGA: 'SET_FILM_VEHICLES_SAGA',
    SET_FILM_SPECIES_SAGA: 'SET_FILM_SPECIES_SAGA',
};