// export const types = {
//     SET_PLANETS_DATA: "SET_PLANETS_DATA",
//     SET_PLANET_INFO_DATA: "SET_PLANET_INFO_DATA",
//     SET_PLANET_FILMS: "SET_PLANET_FILMS",
//     SET_PLANET_RESIDENTS: 'SET_PLANET_RESIDENTS',
// };